
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author administrador
 */
public class PainelDeDesenho extends javax.swing.JPanel {

    public static boolean exibirMalha = false;
    public static boolean pintaQuadrado = false;
    public static int quadradoID = 0;
    public static List<Integer> valoresMalha = new ArrayList<>();
    
    private void contabilizaValoresMalha()
    {
        for ( int i = 2; i <= 500; i++ )
        {
            if ( 500 % i == 0 )
                valoresMalha.add(i);
        }
    }
    
    /**
     * Creates new form NewJPanel
     */
    public PainelDeDesenho() 
    {        
        initComponents();
        contabilizaValoresMalha();
    }

    @Override
    protected void paintComponent(Graphics g) 
    {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        
        if ( pintaQuadrado )
        {
            g.setColor(Color.GREEN);
            int x = (quadradoID % 20) * 25;
            int y = (quadradoID / 20) * 25;
            g.fillRect( x, y, 25, 25);
        }
        
        g.setColor(Color.RED);
        if ( exibirMalha )
        {
            for ( int i = 0; i <= 500; i = i + 25 )
                g.drawLine( i,  0, i, 500 );
        
            for ( int i = 0; i <= 500; i = i + 25 )
                g.drawLine( 0, i, 500, i );
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(java.awt.Color.black);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
